baseURL = "https://nokka.github.io"
languageCode = "en-us"
title = "Stefan Konno"
theme = "minimal"
googleAnalytics = ""
content = ""
enableRobotsTXT = false

[params]
    author = "Stefan Konno"
    description = "Tech ramblings"
    profilePic = "elmo.jpg"
    githubUsername = "nokka"
    copyright = "All opinions expressed are my own and do not reflect those of my employer or anyone else."
    accent = "black"
    showBorder = false
    backgroundColor = "white"
    heading_font = "Lato"
    font = "Merriweather" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "paraiso-dark"
    highlightLanguages = ["go"]
    css = ["/css/override.css"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://github.com/nokka/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/stefan-konno-22b83544/"
    name = "fab fa-linkedin"
    weight = 4
